import type { Metadata } from "next";
import "./globals.css";
import Header from '@/app/layouts/Header'
import Footer from '@/app/layouts/Footer'
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});


export const metadata: Metadata = {
  title: "Creative Space Developers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Header/>        
        {children}
        <Footer/>
      </body>
    </html>
  );
}
