import type { Metadata } from "next";
import "./globals.css";
import Header from '@/app/layouts/Header'
import Footer from '@/app/layouts/Footer'


export const metadata: Metadata = {
  title: "Creative Space Developers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>        
        {children}
        <Footer/>
      </body>
    </html>
  );
}
